## Azure DevOps pipeline: Build & Deploy .NET 8 Web API to Azure App Service
## Adjust the variables below (at minimum: webAppName, azureServiceConnection). Keep secrets in Variable Groups or Library (not here).

trigger:
	branches:
		include:
			- main
	paths:
		include:
			- backend/src/lrembecki.obsluga-it.api/

pr:
	branches:
		include:
			- main

variables:
- name: projectFile
  value: 'backend/src/lrembecki.obsluga-it.api/lrembecki.obsluga-it.api.csproj'
- name: buildConfiguration
  value: 'Release'
- name: dotnetVersion
  value: '8.0.x'

stages:
- stage: build
  jobs:
  - job: build
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetVersion)'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '$(projectFile)'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '$(projectFile)'
        arguments: '--configuration $(buildConfiguration) --no-restore'
