## Azure DevOps pipeline: Build & Deploy .NET 8 Web API to Azure App Service
## Adjust the variables below (at minimum: webAppName, azureServiceConnection). Keep secrets in Variable Groups or Library (not here).

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - backend

pr:
  branches:
    include:
    - main

stages:
- stage: build
  jobs:
  - job: build
    steps:
    - checkout: self
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '/backend'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '/backend'
