// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lrembecki.infrastructure;

#nullable disable

namespace lrembecki.infrastructure.Migrations
{
    [DbContext(typeof(ObslugaItDbContext))]
    [Migration("20260119224108_TrotamundosPagesHome-202601192340")]
    partial class TrotamundosPagesHome202601192340
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountPermissionGroup", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountId", "PermissionGroupId");

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("AccountPermissionGroup", "app");
                });

            modelBuilder.Entity("AccountSubscriptionPermissionGroup", b =>
                {
                    b.Property<Guid>("AccountSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountSubscriptionId", "PermissionGroupId");

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("AccountSubscriptionPermissionGroup", "app");
                });

            modelBuilder.Entity("CompanyEmailContact", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("CompanyEmailContact", "app");
                });

            modelBuilder.Entity("CompanyPhoneContact", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("CompanyPhoneContact", "app");
                });

            modelBuilder.Entity("EmailTemplate_Contacts_Bcc", b =>
                {
                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmailTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContactId", "EmailTemplateId");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("EmailTemplate_Contacts_Bcc", "app");
                });

            modelBuilder.Entity("EmailTemplate_Contacts_Cc", b =>
                {
                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmailTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContactId", "EmailTemplateId");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("EmailTemplate_Contacts_Cc", "app");
                });

            modelBuilder.Entity("EmailTemplate_Contacts_To", b =>
                {
                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmailTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContactId", "EmailTemplateId");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("EmailTemplate_Contacts_To", "app");
                });

            modelBuilder.Entity("PermissionGroupPermission", b =>
                {
                    b.Property<Guid>("PermissionGrupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionGrupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("PermissionGroupPermission", "app");
                });

            modelBuilder.Entity("TrotamundosTripAdvantage", b =>
                {
                    b.Property<Guid>("AdvantageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AdvantageId", "TripId");

                    b.HasIndex("TripId");

                    b.ToTable("TrotamundosTripAdvantage", "app");
                });

            modelBuilder.Entity("lrembecki.core.account.AccountSubscriptions.AccountSubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("AccountSubscription", "app");
                });

            modelBuilder.Entity("lrembecki.core.account.Accounts.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Account", "app");
                });

            modelBuilder.Entity("lrembecki.core.account.PermissionGroups.PermissionGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PermissionGroup", "app");
                });

            modelBuilder.Entity("lrembecki.core.account.Permissions.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permission", "app");
                });

            modelBuilder.Entity("lrembecki.core.forms.FormDefinitions.FormDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("FormDefinition", "app");
                });

            modelBuilder.Entity("lrembecki.core.forms.Forms.FormEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormDefinitionId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Form", "app");
                });

            modelBuilder.Entity("lrembecki.core.settings.Address.AddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Address", "app");
                });

            modelBuilder.Entity("lrembecki.core.settings.Companies.CompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Company", "app");
                });

            modelBuilder.Entity("lrembecki.core.settings.Contacts.ContactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Contact", "app");
                });

            modelBuilder.Entity("lrembecki.core.settings.EmailTemplates.EmailTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateHtmlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TemplateHtmlId")
                        .IsUnique();

                    b.ToTable("EmailTemplate", "app");
                });

            modelBuilder.Entity("lrembecki.core.settings.EmailTemplates.EmailTemplateFieldEntity", b =>
                {
                    b.Property<Guid>("EmailTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmailTemplateId", "FieldName");

                    b.ToTable("EmailTemplateField", "app");
                });

            modelBuilder.Entity("lrembecki.core.settings.Emails.EmailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ReplyToAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReplyToName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SmtpUsername")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Email", "app");
                });

            modelBuilder.Entity("lrembecki.core.settings.Notifications.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Notification", "app");
                });

            modelBuilder.Entity("lrembecki.core.settings.Website.WebsiteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Website", "app");
                });

            modelBuilder.Entity("lrembecki.core.settings.Website.WebsiteMetaEntity", b =>
                {
                    b.Property<Guid>("WebsiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Keywords")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("WebsiteId");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("WebsiteMeta", "app");
                });

            modelBuilder.Entity("lrembecki.core.shared.Subscriptions.SubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subscription", "app");
                });

            modelBuilder.Entity("lrembecki.core.storage.FileStorageEntity", b =>
                {
                    b.Property<Guid>("StorageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("StorageId");

                    b.ToTable("FileStorage", "app");
                });

            modelBuilder.Entity("lrembecki.core.storage.ImageStorageEntity", b =>
                {
                    b.Property<Guid>("StorageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("Height")
                        .HasColumnType("bigint");

                    b.Property<long>("Width")
                        .HasColumnType("bigint");

                    b.HasKey("StorageId");

                    b.ToTable("ImageStorage", "app");
                });

            modelBuilder.Entity("lrembecki.core.storage.StorageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Storage", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Advantages.AdvantageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("TrotamundosAdvantage", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Files.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StorageId")
                        .IsUnique();

                    b.HasIndex("SubscriptionId");

                    b.ToTable("TrotamundosFile", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Highlights.HighlightEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("TrotamundosHighlight", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.LoyalityPrograms.LoyalityProgramEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("TripEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TripEntityId");

                    b.ToTable("TrotamundosLoyalityProgram", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.AboutUs.AboutUsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("TrotamundosPagesAboutUs", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.AboutUs.AboutUsItemEntity", b =>
                {
                    b.Property<Guid>("AboutUsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AboutUsId", "Order");

                    b.ToTable("TrotamundosPagesAboutUsItem", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.AboutUs.AboutUsPersonEntity", b =>
                {
                    b.Property<Guid>("AboutUsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("AboutUsEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AboutUsId", "Order");

                    b.HasIndex("AboutUsEntityId");

                    b.HasIndex("ImageId");

                    b.ToTable("TrotamundosPagesAboutUsPerson", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.Home.HomeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BackgroundVideoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrailerVideoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundVideoId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TrailerVideoId");

                    b.ToTable("TrotamundosPagesHome", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.Home.HomeOpinionEntity", b =>
                {
                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HomeId", "Order");

                    b.HasIndex("ImageId");

                    b.ToTable("TrotamundosPagesHomeOpinion", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.HowItWorks.HowItWorksEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FooterText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("TrotamundosPagesHowItWorks", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.HowItWorks.HowItWorksItemEntity", b =>
                {
                    b.Property<Guid>("HowItWorksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("HowItWorksId", "Order");

                    b.HasIndex("ImageId");

                    b.ToTable("TrotamundosPagesHowItWorksItem", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripAgendaEntity", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("TripId", "Order");

                    b.ToTable("TrotamundosTripAgenda", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Calendar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SuggestedFlightNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("TrotamundosTrip", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripHighlightEntity", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HighlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TripId", "HighlightId");

                    b.HasIndex("HighlightId");

                    b.ToTable("TrotamundosTripHighlight", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripImageEntity", b =>
                {
                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageId");

                    b.HasIndex("TripId");

                    b.ToTable("TrotamundosTripImage", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripPaymentScheduleEntity", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TripId", "Order");

                    b.ToTable("TrotamundosTripPaymentSchedule", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripPriceIncludeEntity", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("Includes")
                        .HasColumnType("bit");

                    b.HasKey("TripId", "Order");

                    b.ToTable("TrotamundosTripPriceInclude", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripRequirementEntity", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("TripId", "Order");

                    b.ToTable("TrotamundosTripRequirement", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripScheduleEntity", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TripId", "Order");

                    b.ToTable("TrotamundosTripSchedule", "app");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripSuggestedFlightEntity", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TripId", "Order");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("TrotamundosTripSuggestedFlight", "app");
                });

            modelBuilder.Entity("AccountPermissionGroup", b =>
                {
                    b.HasOne("lrembecki.core.account.Accounts.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lrembecki.core.account.PermissionGroups.PermissionGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccountSubscriptionPermissionGroup", b =>
                {
                    b.HasOne("lrembecki.core.account.AccountSubscriptions.AccountSubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lrembecki.core.account.PermissionGroups.PermissionGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyEmailContact", b =>
                {
                    b.HasOne("lrembecki.core.settings.Companies.CompanyEntity", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.settings.Contacts.ContactEntity", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyPhoneContact", b =>
                {
                    b.HasOne("lrembecki.core.settings.Companies.CompanyEntity", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.settings.Contacts.ContactEntity", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EmailTemplate_Contacts_Bcc", b =>
                {
                    b.HasOne("lrembecki.core.settings.Contacts.ContactEntity", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.settings.EmailTemplates.EmailTemplateEntity", null)
                        .WithMany()
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EmailTemplate_Contacts_Cc", b =>
                {
                    b.HasOne("lrembecki.core.settings.Contacts.ContactEntity", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.settings.EmailTemplates.EmailTemplateEntity", null)
                        .WithMany()
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EmailTemplate_Contacts_To", b =>
                {
                    b.HasOne("lrembecki.core.settings.Contacts.ContactEntity", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.settings.EmailTemplates.EmailTemplateEntity", null)
                        .WithMany()
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionGroupPermission", b =>
                {
                    b.HasOne("lrembecki.core.account.PermissionGroups.PermissionGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionGrupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lrembecki.core.account.Permissions.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrotamundosTripAdvantage", b =>
                {
                    b.HasOne("lrembecki.core.trotamundos.Advantages.AdvantageEntity", null)
                        .WithMany()
                        .HasForeignKey("AdvantageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.trotamundos.Trips.TripEntity", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.account.AccountSubscriptions.AccountSubscriptionEntity", b =>
                {
                    b.HasOne("lrembecki.core.account.Accounts.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("lrembecki.core.forms.FormDefinitions.FormDefinitionEntity", b =>
                {
                    b.HasOne("lrembecki.core.settings.Notifications.NotificationEntity", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("lrembecki.core.forms.FormDefinitions.FormDefinitionEmailNotificationFieldMappingEntity", "EmailNotificationFieldMapping", b1 =>
                        {
                            b1.Property<Guid>("FormDefinitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FormDefinitionFieldName")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("EmailTemplateFieldName")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.HasKey("FormDefinitionId", "FormDefinitionFieldName", "EmailTemplateFieldName");

                            b1.ToTable("FormDefinitionEmailNotificationMapping", "app");

                            b1.WithOwner()
                                .HasForeignKey("FormDefinitionId");
                        });

                    b.OwnsMany("lrembecki.core.forms.FormDefinitions.FormFieldDefinitionEntity", "Fields", b1 =>
                        {
                            b1.Property<Guid>("FormDefinitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FieldName")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("FieldType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("bit");

                            b1.HasKey("FormDefinitionId", "FieldName");

                            b1.ToTable("FormDefinitionField", "app");

                            b1.WithOwner()
                                .HasForeignKey("FormDefinitionId");
                        });

                    b.Navigation("EmailNotificationFieldMapping");

                    b.Navigation("Fields");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("lrembecki.core.forms.Forms.FormEntity", b =>
                {
                    b.HasOne("lrembecki.core.forms.FormDefinitions.FormDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("FormDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("lrembecki.core.forms.Forms.FormFieldEntity", "Fields", b1 =>
                        {
                            b1.Property<Guid>("FormId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<Guid>("FormEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.HasKey("FormId", "Name");

                            b1.HasIndex("FormEntityId");

                            b1.ToTable("FormField", "app");

                            b1.WithOwner()
                                .HasForeignKey("FormEntityId");
                        });

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("lrembecki.core.settings.Address.AddressEntity", b =>
                {
                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.settings.Companies.CompanyEntity", b =>
                {
                    b.HasOne("lrembecki.core.settings.Address.AddressEntity", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("lrembecki.core.settings.Companies.CompanyParameterEntity", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("CompanyId", "Order");

                            b1.ToTable("CompanyParameter", "app");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("lrembecki.core.settings.Contacts.ContactEntity", b =>
                {
                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.settings.EmailTemplates.EmailTemplateEntity", b =>
                {
                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lrembecki.core.storage.StorageEntity", "TemplateHtml")
                        .WithOne()
                        .HasForeignKey("lrembecki.core.settings.EmailTemplates.EmailTemplateEntity", "TemplateHtmlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TemplateHtml");
                });

            modelBuilder.Entity("lrembecki.core.settings.EmailTemplates.EmailTemplateFieldEntity", b =>
                {
                    b.HasOne("lrembecki.core.settings.EmailTemplates.EmailTemplateEntity", null)
                        .WithMany("Fields")
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.settings.Emails.EmailEntity", b =>
                {
                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.settings.Notifications.NotificationEntity", b =>
                {
                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("lrembecki.core.settings.Notifications.EmailNotificationEntity", "Email", b1 =>
                        {
                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("EmailId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("EmailTemplateId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("NotificationId");

                            b1.HasIndex("EmailId");

                            b1.HasIndex("EmailTemplateId");

                            b1.ToTable("NotificationEmail", "app");

                            b1.HasOne("lrembecki.core.settings.Emails.EmailEntity", "Email")
                                .WithMany()
                                .HasForeignKey("EmailId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("lrembecki.core.settings.EmailTemplates.EmailTemplateEntity", "EmailTemplate")
                                .WithMany()
                                .HasForeignKey("EmailTemplateId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("NotificationId");

                            b1.Navigation("Email");

                            b1.Navigation("EmailTemplate");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.settings.Website.WebsiteEntity", b =>
                {
                    b.HasOne("lrembecki.core.settings.Companies.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("lrembecki.core.settings.Website.WebsiteMetaEntity", b =>
                {
                    b.HasOne("lrembecki.core.storage.StorageEntity", "Image")
                        .WithOne()
                        .HasForeignKey("lrembecki.core.settings.Website.WebsiteMetaEntity", "ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.settings.Website.WebsiteEntity", null)
                        .WithOne("Meta")
                        .HasForeignKey("lrembecki.core.settings.Website.WebsiteMetaEntity", "WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("lrembecki.core.storage.FileStorageEntity", b =>
                {
                    b.HasOne("lrembecki.core.storage.StorageEntity", null)
                        .WithOne("File")
                        .HasForeignKey("lrembecki.core.storage.FileStorageEntity", "StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.storage.ImageStorageEntity", b =>
                {
                    b.HasOne("lrembecki.core.storage.StorageEntity", null)
                        .WithOne("Image")
                        .HasForeignKey("lrembecki.core.storage.ImageStorageEntity", "StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.storage.StorageEntity", b =>
                {
                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Advantages.AdvantageEntity", b =>
                {
                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Files.FileEntity", b =>
                {
                    b.HasOne("lrembecki.core.storage.StorageEntity", "Storage")
                        .WithOne()
                        .HasForeignKey("lrembecki.core.trotamundos.Files.FileEntity", "StorageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Highlights.HighlightEntity", b =>
                {
                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.LoyalityPrograms.LoyalityProgramEntity", b =>
                {
                    b.HasOne("lrembecki.core.storage.StorageEntity", "Image")
                        .WithOne()
                        .HasForeignKey("lrembecki.core.trotamundos.LoyalityPrograms.LoyalityProgramEntity", "ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lrembecki.core.trotamundos.Trips.TripEntity", null)
                        .WithMany("LoyalityPrograms")
                        .HasForeignKey("TripEntityId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.AboutUs.AboutUsEntity", b =>
                {
                    b.HasOne("lrembecki.core.storage.StorageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.AboutUs.AboutUsItemEntity", b =>
                {
                    b.HasOne("lrembecki.core.trotamundos.Pages.AboutUs.AboutUsEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("AboutUsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.AboutUs.AboutUsPersonEntity", b =>
                {
                    b.HasOne("lrembecki.core.trotamundos.Pages.AboutUs.AboutUsEntity", null)
                        .WithMany("Persons")
                        .HasForeignKey("AboutUsEntityId");

                    b.HasOne("lrembecki.core.storage.StorageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.Home.HomeEntity", b =>
                {
                    b.HasOne("lrembecki.core.storage.StorageEntity", "BackgroundVideo")
                        .WithMany()
                        .HasForeignKey("BackgroundVideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lrembecki.core.storage.StorageEntity", "TrailerVideo")
                        .WithMany()
                        .HasForeignKey("TrailerVideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BackgroundVideo");

                    b.Navigation("TrailerVideo");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.Home.HomeOpinionEntity", b =>
                {
                    b.HasOne("lrembecki.core.trotamundos.Pages.Home.HomeEntity", null)
                        .WithMany("Opinions")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lrembecki.core.storage.StorageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.HowItWorks.HowItWorksEntity", b =>
                {
                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.HowItWorks.HowItWorksItemEntity", b =>
                {
                    b.HasOne("lrembecki.core.trotamundos.Pages.HowItWorks.HowItWorksEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("HowItWorksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lrembecki.core.storage.StorageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripAgendaEntity", b =>
                {
                    b.HasOne("lrembecki.core.trotamundos.Trips.TripEntity", null)
                        .WithMany("Agenda")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripEntity", b =>
                {
                    b.HasOne("lrembecki.core.shared.Subscriptions.SubscriptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripHighlightEntity", b =>
                {
                    b.HasOne("lrembecki.core.trotamundos.Highlights.HighlightEntity", null)
                        .WithMany()
                        .HasForeignKey("HighlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.trotamundos.Trips.TripEntity", null)
                        .WithMany("Highlights")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripImageEntity", b =>
                {
                    b.HasOne("lrembecki.core.storage.StorageEntity", "Image")
                        .WithOne()
                        .HasForeignKey("lrembecki.core.trotamundos.Trips.TripImageEntity", "ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.trotamundos.Trips.TripEntity", null)
                        .WithMany("Images")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripPaymentScheduleEntity", b =>
                {
                    b.HasOne("lrembecki.core.trotamundos.Trips.TripEntity", null)
                        .WithMany("PaymentSchedules")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripPriceIncludeEntity", b =>
                {
                    b.HasOne("lrembecki.core.trotamundos.Trips.TripEntity", null)
                        .WithMany("PriceIncludes")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripRequirementEntity", b =>
                {
                    b.HasOne("lrembecki.core.trotamundos.Trips.TripEntity", null)
                        .WithMany("Requirements")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripScheduleEntity", b =>
                {
                    b.HasOne("lrembecki.core.trotamundos.Trips.TripEntity", null)
                        .WithMany("Schedules")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripSuggestedFlightEntity", b =>
                {
                    b.HasOne("lrembecki.core.storage.StorageEntity", "Image")
                        .WithOne()
                        .HasForeignKey("lrembecki.core.trotamundos.Trips.TripSuggestedFlightEntity", "ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lrembecki.core.trotamundos.Trips.TripEntity", null)
                        .WithMany("SuggestedFlights")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("lrembecki.core.settings.EmailTemplates.EmailTemplateEntity", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("lrembecki.core.settings.Website.WebsiteEntity", b =>
                {
                    b.Navigation("Meta")
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.storage.StorageEntity", b =>
                {
                    b.Navigation("File")
                        .IsRequired();

                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.AboutUs.AboutUsEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.Home.HomeEntity", b =>
                {
                    b.Navigation("Opinions");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Pages.HowItWorks.HowItWorksEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("lrembecki.core.trotamundos.Trips.TripEntity", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("Highlights");

                    b.Navigation("Images");

                    b.Navigation("LoyalityPrograms");

                    b.Navigation("PaymentSchedules");

                    b.Navigation("PriceIncludes");

                    b.Navigation("Requirements");

                    b.Navigation("Schedules");

                    b.Navigation("SuggestedFlights");
                });
#pragma warning restore 612, 618
        }
    }
}
